<?
/* make trans_check.pl happy
GetMessage('TASK_NAME_IBLOCK_DENY');
GetMessage('TASK_NAME_IBLOCK_READ');
GetMessage('TASK_NAME_IBLOCK_EDIT');
GetMessage('TASK_NAME_IBLOCK_FULL');
GetMessage('TASK_NAME_SECTION_DENY');
GetMessage('TASK_NAME_SECTION_READ');
GetMessage('TASK_NAME_SECTION_LIMITED_EDIT');
GetMessage('TASK_NAME_SECTION_FULL_EDIT');
GetMessage('TASK_NAME_SECTION_FULL');
*/
?>