var MESS = {
	'ru': {
		'add': 'Добавить',
		'title': 'Bitrix OTP',
		'wait': 'Пожалуйста, подождите....',
		'sitebut': 'Сайты',
		'pwdtitle': 'Пароль',
		'edit': 'Изменить',
		'yourpwd': 'Ваш одноразовый пароль для сайта:',
		'getpwd': 'Получить пароль',
		'getpwd2': 'Получить другой пароль',
		'notespwd': 'Одноразовый пароль (см. 2 на рисунке) вводится в поле "Пароль" стандартной формы авторизации на сайте сразу после обычного пароля (см. 1 на рисунке) без пробелов:<br><br><img src="./images/ru_pass_form.jpg">',
		'cancel': 'Отменить',
		'newtitle': 'Новый сайт',
		'next': 'Далее',
		'url': 'Адрес сайта:',
		'descr':'Описание:',
		'login':'Имя входа на сайт:',
		'password':'Пароль:',
		'captcha':'Защита:',
		'capt':'Введите текст на картинке',
		'save':'Сохранить',
		'secret':'Секретный ключ:',
		'delete':'Удалить',
		'deltitle':'Удаление',
		'delwarn':'Внимание! Вся информация связанная с авторизацией на сайте будет удалена. Для корректного удаления необходимо разрегистрировать устройство на сайте.',
		'unreg':'Разрегистрировать устройство:',
		'no':'Нет',
		'yes':'Да',
		'password2':'Пароль (без одноразового пароля OTP):',
		'edittitle':'Редактирование',
		'entcapt':'Введите текст на картинке',
		'confupdate':'Доступна новая версия приложения. Загрузить?',
		'alertsave':'Ошибка сохранения в локальную базу данных:',
		'alertlogin':'Введите имя входа и пароль для разрегистрации на сайте.',
		'confdelete1':'Ошибка при разрегистрации устройства на сайте. Неверно введен логин и пароль. Удалить сведения о сайте без снятия регистрации (не рекомендуется)?',
		'confdelete2':'При разрегистрации устройства на сайте произошла ошибка',
		'confdelete3':'Удалить сведения о сайте без снятия регистрации (не рекомендуется)?',
		'alerturl':'Введите адрес сайта.',
		'alertdesc':'Введите описание сайта.',
		'alertsecret':'Введите секретный ключ.',
		'alertinet':'Для добавления нового сайта необходимо подключение к сети Интернет. Подключитесь и попробуйте еще раз.',
		'alertpass':'Введите имя входа и пароль для регистрации на сайте.',
		'alertablogin':'Ошибка при регистрации устройства на сайте. Неверно введен логин и пароль.',
		'alertregerr1':'Ошибка при регистрации устройства на сайте.',
		'alertregerr2':'Возможно данный сайт не поддерживает авторизацию с OTP. Сохранить настройки сайта все равно?',
		'inst':'<div style="text-align: center;"><img src="images/ru_logo.png"></div><h4>Добро пожаловать в Bitrix OTP - программу генерации одноразовых паролей!</h4>При помощи этого приложения вы сможете более безопасно посещать сайты в сети Интернет.<br>Для установки приложения необходимо разместить его на рабочем столе. Для этого нажмите в safari на кнопку добавления #icon# и выберите "Добавить в Домой".',
		'addnew':'<h4>Воспользуйтесь кнопкой в правом верхнем углу, чтобы добавить сайт.</h4><a href="http://www.1c-bitrix.ru/?r1=mobile&r2=otp"><img border="0" src="./images/ru_logo.png"></a> ',
		'req':'Обязательно'
	},
	'en': {
		'add': 'Add',
		'title': 'Bitrix OTP',
		'wait': 'Please wait...',
		'sitebut': 'Sites',
		'pwdtitle': 'Password',
		'edit': 'Edit',
		'yourpwd': 'Your one time password:',
		'getpwd': 'Get Password',
		'getpwd2': 'Get Another Password',
		'notespwd': 'Type your one time password (see 2 on the figure) in the "Password" field right after the standard password (see 1 on the figure) without space, in the authorization form:<br><br><img src="images/en_pass_form.jpg">',
		'cancel': 'Cancel',
		'newtitle': 'New Website',
		'next': 'Next',
		'url': 'Site URL:',
		'descr': 'Description:',
		'login': 'Login:',
		'password': 'Password:',
		'captcha': 'CAPTCHA:',
		'capt': 'Enter the CAPTCHA code',
		'save': 'Save',
		'secret': 'Secret Key:',
		'delete': 'Delete',
		'deltitle': 'Delete',
		'delwarn': 'Attention! All the authorization information will be deleted. You have to unregister your device at the website for correct removal.',
		'unreg': 'Unregister Device:',
		'no': 'No',
		'yes': 'Yes',
		'password2': 'Password (without OTP):',
		'edittitle': 'Edit',
		'entcapt': 'Enter the CAPTCHA code',
		'confupdate': 'A new version is available. Download?',
		'alertsave': 'Error saving data to the local database:',
		'alertlogin': 'Enter your login and password to unregister.',
		'confdelete1': 'Failed to unregister the device because the login and/or password are incorrect. Delete website information without unregistering (not recommended)?',
		'confdelete2': 'Error unregistering the device',
		'confdelete3': 'Delete website information without unregistering (not recommended)?',
		'alerturl': 'The website address is required.',
		'alertdesc': 'The website description is required.',
		'alertsecret': 'The secret key is required.',
		'alertinet': 'You must be connected to the Internet before adding a new website. Please connect and try again.',
		'alertpass': 'Enter the login and password to register.',
		'alertablogin': 'Error registering the device. The login and/or password are incorrect.',
		'alertregerr1': 'Error registering the device.',
		'alertregerr2': 'This site may not support OTP authorization. Save website settings anyway?',
		'inst': '<div style="text-align: center;"><img src="images/en_logo.png"></div><h4>Welcome to Bitrix OTP, the OTP generation software!</h4>Use this application for safe and secure website browsing in the Internet.<br>To install the application, you have to place it on your desktop. Click the  button #icon# in your Safari browser and select "Add to Home Screen".',
		'addnew': '<h4>Use the button in the top right corner to add a website.</h4><a href="http://www.bitrixsoft.com/?r1=mobile&r2=otp"><img border="0" src="images/en_logo.png"></a>',
		'req': 'Required'
	},
	'de': { 
		'add': 'Hinzufügen', 
		'title': 'Bitrix OTP', 
		'wait': 'Bitte warten…', 
		'sitebut': 'Websites', 
		'pwdtitle': 'Passwort', 
		'edit': 'Bearbeiten', 
		'yourpwd': 'Ihr Einmalpasswort lautet:', 
		'getpwd': 'Passwort anfordern', 
		'getpwd2': 'Ein anderes Passwort anfordern', 
		'notespwd': 'Das Einmalpasswort (siehe 2 auf der Abbildung) wird in der Anmeldemaske im Feld "Passwort" direkt nach dem eigenen Passwort (siehe 1 auf der Abbildung) ohne Leerzeichen eingegeben:<br><br><img src="images/de_pass_form.jpg">', 
		'cancel': 'Abbrechen', 
		'newtitle': 'Neue Website', 
		'next': 'Weiter', 
		'url': 'Website-URL:', 
		'descr':'Beschreibung:', 
		'login':'Login.', 
		'password':'Passwort:', 
		'captcha':'CAPTCHA:', 
		'capt':'Geben Sie den CAPTCHA-Code ein', 
		'save':'Speichern', 
		'secret':'Geheimcode:', 
		'delete':'Löschen', 
		'deltitle':'Löschen', 
		'delwarn':'Achtung! Alle Autorisierungsinformationen werden gelöscht. Sie müssen Ihr Gerät von der Website abmelden, um es korrekt zu entfernen.', 
		'unreg':'Gerät abmelden:', 
		'no':'Nein', 
		'yes':'Ja', 
		'password2':'Passwort (ohne OTP):', 
		'edittitle':'Bearbeiten', 
		'entcapt':'Geben Sie den CAPTCHA-Code ein', 
		'confupdate':'Eine neue Version ist verfügbar. Herunterladen?', 
		'alertsave':'Fehler beim Speichern in die lokale Datenbank:', 
		'alertlogin':'Geben Sie den Login und das Passwort zur Abmeldung ein.', 
		'confdelete1':'Fehler beim Abmelden des Gerätes auf der Website. Der Login und/oder das Passwort wurden nicht korrekt eingegeben. Sollen die Website-Informationen ohne Abmeldung gelöscht werden (nicht empfohlen)?', 
		'confdelete2':'Beim Abmelden des Gerätes auf der Website ist ein Fehler aufgetreten', 
		'confdelete3':'Sollen die Website-Informationen ohne Abmeldung gelöscht werden (nicht empfohlen)?', 
		'alerturl':'Website-Adresse ist erforderlich.', 
		'alertdesc':'Website-Beschreibung ist erforderlich.', 
		'alertsecret':'Geheimcode ist erforderlich.', 
		'alertinet':'Sie müssen über eine Internetverbindung verfügen, bevor Sie eine neue Website hinzufügen. Stellen Sie die Verbindung her, dann versuchen Sie erneut.', 
		'alertpass':'Geben Sie Login und Passwort zur Anmeldung ein.', 
		'alertablogin':'Fehler beim Anmelden des Gerätes auf der Website. Login und/oder Passwort sind nicht korrekt.', 
		'alertregerr1':'Fehler beim Anmelden des Gerätes auf der Website.', 
		'alertregerr2':'OTP-Autorisierung wird von dieser Website möglicherweise nicht unterstützt. Sollen die Website-Einstellungen trotzdem gespeichert werden?',
		'inst':'<div style="text-align: center;"><img src="images/en_logo.png"></div><h4>Willkommen bei Bitrix OTP, einer Software zur Generierung von Einmalpasswörtern.</h4>Benutzen Sie diese Anwendung für sicheres Surfen im Internet.<br>Um diese Anwendung zu installieren, müssen Sie sie auf Ihrem Home-Bildschirm platzieren. Klicken Sie dafür auf die Schaltfläche #icon# in Ihrem Safari-Browser und wählen Sie die Option "Zum Home-Bildschirm" hinzufügen aus.', 
		'addnew':'<h4>Benutzen Sie die Schaltfläche in der oberen rechten Ecke, um die Website hinzuzufügen.</h4><a href="http://www.bitrix.de/?r1=mobile&r2=otp"><img border="0" src="images/en_logo.png"></a>', 
		'req':'Erforderlich' 
	}
};
